import { defineScript } from "rwsdk/worker";
import { db, setupDb } from "@/db";
import bcrypt from "bcryptjs";

const CATEGORIES = ["NLP", "Computer Vision", "Audio", "Multimodal", "Code", "Tabular"];
const STATUSES = ["active", "active", "active", "inactive", "pending"] as const;
const SOURCES = [
  "OpenAI Ada-002",
  "OpenAI text-embedding-3-large",
  "Cohere embed-english-v3",
  "Google Vertex AI",
  "HuggingFace BAAI/bge-large-en",
  "Mistral Embed",
];

function makeVector(dim: number) {
  return Array.from({ length: dim }, () =>
    parseFloat((Math.random() * 2 - 1).toFixed(6)),
  );
}

const SEED_RECORDS = [
  {
    label: "Product review embedding — positive sentiment",
    description:
      "Dense embedding of a positive product review extracted from an e-commerce dataset using Ada-002. Used for semantic similarity search across the reviews corpus.",
    category: "NLP",
    source: SOURCES[0],
    tags: JSON.stringify(["review", "sentiment", "e-commerce"]),
    numericValue: 0.8721,
    confidence: 0.9512,
    status: "active",
    metadata: JSON.stringify({
      model_version: "ada-002",
      input_tokens: 312,
      language: "en",
      dataset: "amazon-reviews-2024",
    }),
  },
  {
    label: "ResNet-50 feature map — street scene",
    description:
      "Image embedding generated by a fine-tuned ResNet-50 backbone on the COCO dataset. Represents a busy city intersection captured at dusk.",
    category: "Computer Vision",
    source: SOURCES[1],
    tags: JSON.stringify(["image", "coco", "street", "resnet"]),
    numericValue: 0.3456,
    confidence: 0.8834,
    status: "active",
    metadata: JSON.stringify({
      image_width: 1920,
      image_height: 1080,
      capture_date: "Nov 04, 2025",
      capture_hour: "18:23 UTC",
      location: "Berlin, DE",
    }),
  },
  {
    label: "Audio segment — spoken command classification",
    description:
      "Mel-spectrogram embedding of a 2-second spoken command clip. Part of the wake-word detection training pipeline.",
    category: "Audio",
    source: SOURCES[2],
    tags: JSON.stringify(["audio", "speech", "command", "wake-word"]),
    numericValue: 0.6103,
    confidence: 0.7241,
    status: "active",
    metadata: JSON.stringify({
      duration_sec: 2.0,
      sample_rate: 16000,
      speaker_id: "spk_00421",
      noise_level_db: -24,
    }),
  },
  {
    label: "Code snippet — Python async iterator",
    description:
      "Semantic embedding of a Python code snippet implementing an async iterator pattern. Used for code search and auto-complete ranking.",
    category: "Code",
    source: SOURCES[4],
    tags: JSON.stringify(["python", "async", "iterator", "code-search"]),
    numericValue: 0.5502,
    confidence: 0.9021,
    status: "active",
    metadata: JSON.stringify({
      language: "python",
      lines_of_code: 28,
      repo: "internal-utils",
      complexity_score: 4.2,
    }),
  },
  {
    label: "Multimodal — product image + description",
    description:
      "Joint embedding of a product image and its textual description, produced by a CLIP-style multimodal model. Used for cross-modal retrieval.",
    category: "Multimodal",
    source: "OpenCLIP ViT-H-14",
    tags: JSON.stringify(["clip", "multimodal", "product", "retrieval"]),
    numericValue: 0.7789,
    confidence: 0.8612,
    status: "active",
    metadata: JSON.stringify({
      image_model: "ViT-H-14",
      text_model: "GPT-2 tokenizer",
      fusion: "concat-project",
      modalities: ["image", "text"],
    }),
  },
  {
    label: "Tabular row — credit risk features",
    description:
      "Dense projection of a tabular credit-risk record (35 features) into embedding space via a learned encoder. Used for anomaly detection.",
    category: "Tabular",
    source: SOURCES[3],
    tags: JSON.stringify(["tabular", "finance", "credit", "anomaly"]),
    numericValue: 0.2134,
    confidence: 0.6389,
    status: "pending",
    metadata: JSON.stringify({
      original_features: 35,
      encoder_type: "MLP",
      scaler: "standard",
      dataset_version: "v3.1",
    }),
  },
  {
    label: "Legal document — contract clause NLP embedding",
    description:
      "Embedding of a contract indemnification clause extracted from a commercial SaaS agreement. Part of clause similarity search pipeline.",
    category: "NLP",
    source: SOURCES[2],
    tags: JSON.stringify(["legal", "contract", "nlp", "clause"]),
    numericValue: 0.4231,
    confidence: 0.8105,
    status: "active",
    metadata: JSON.stringify({
      document_type: "SaaS Agreement",
      clause_type: "Indemnification",
      jurisdiction: "US",
      word_count: 218,
    }),
  },
  {
    label: "Medical image — chest X-ray pathology embedding",
    description:
      "Embedding of a chest radiograph processed through a DenseNet-121 model pre-trained on CheXpert. Flagged for follow-up review.",
    category: "Computer Vision",
    source: "DenseNet-121/CheXpert",
    tags: JSON.stringify(["medical", "xray", "chest", "pathology"]),
    numericValue: 0.9021,
    confidence: 0.5677,
    status: "inactive",
    metadata: JSON.stringify({
      patient_age_group: "50-60",
      view: "PA",
      pathology_flags: ["Atelectasis", "Effusion"],
      model_version: "densenet-chexpert-v2",
    }),
  },
  {
    label: "Scientific abstract — genomics paper",
    description:
      "Embedding of the abstract of a published genomics paper from PubMed. Used in a semantic literature search engine for bioinformatics researchers.",
    category: "NLP",
    source: SOURCES[5],
    tags: JSON.stringify(["science", "genomics", "pubmed", "bioinformatics"]),
    numericValue: 0.6644,
    confidence: 0.9234,
    status: "active",
    metadata: JSON.stringify({
      pubmed_id: "39012847",
      journal: "Nature Genomics",
      year: 2025,
      keyword_count: 8,
    }),
  },
  {
    label: "Customer support ticket — high priority classification",
    description:
      "Embedding of a customer support ticket body text. Classified as high-priority based on similarity to past escalation patterns.",
    category: "NLP",
    source: SOURCES[0],
    tags: JSON.stringify(["support", "ticket", "classification", "nlp"]),
    numericValue: 0.1987,
    confidence: 0.7856,
    status: "active",
    metadata: JSON.stringify({
      ticket_id: "TKT-88201",
      channel: "email",
      priority: "high",
      response_time_target_hours: 4,
    }),
  },
];

export default defineScript(async ({ env }) => {
  setupDb(env);

  const hashedPassword = await bcrypt.hash("password123", 10);

  // Clean existing data
  await db.auditLog.deleteMany();
  await db.vectorRecord.deleteMany();
  await db.user.deleteMany();

  // Create admin user
  const adminUser = await db.user.create({
    data: {
      id: crypto.randomUUID(),
      username: "adminuser",
      password: hashedPassword,
      email: "admin@example.com",
      verified: true,
      role: "ADMIN",
    },
  });

  // Create regular user
  await db.user.create({
    data: {
      id: crypto.randomUUID(),
      username: "testuser",
      password: hashedPassword,
      email: "testuser@example.com",
      verified: true,
      role: "USER",
    },
  });

  // const VECTOR_DIM = 1536;

  // for (const rec of SEED_RECORDS) {
  //   const vector = makeVector(VECTOR_DIM);
  //   await db.vectorRecord.create({
  //     data: {
  //       id: crypto.randomUUID(),
  //       label: rec.label,
  //       description: rec.description,
  //       category: rec.category,
  //       source: rec.source,
  //       tags: rec.tags,
  //       numericValue: rec.numericValue,
  //       confidence: rec.confidence,
  //       vector: JSON.stringify(vector),
  //       dimension: VECTOR_DIM,
  //       metadata: rec.metadata,
  //       status: rec.status,
  //       version: 1,
  //       createdById: adminUser.id,
  //     },
  //   });
  // }

  console.log("🌱 Seeded: 2 users (adminuser / testuser) + 10 vector records");
  console.log("   Passwords: password123");
});
