"use client";

import { useState, useTransition } from "react";
import { insertTableRow } from "./actions";
import type { TableColumnInfo } from "./postgres";

type Props = {
  connectionId: string;
  schemaName: string;
  tableName: string;
  columns: TableColumnInfo[];
  canMutate: boolean;
};

const fieldLabelClass = "text-[0.72rem] font-bold tracking-[0.1em] uppercase text-[var(--c-text-muted)]";
const fieldInputClass =
  "w-full px-2.5 py-1.5 border border-[var(--c-border-input)] rounded-lg bg-[var(--c-bg-input)] text-[var(--c-text)] text-sm outline-none transition-[border-color,box-shadow] focus:border-[var(--c-accent-focus)] focus:shadow-[0_0_0_3px_var(--c-accent-ring)]";
const fieldTextareaClass =
  "w-full px-2.5 py-2 border border-[var(--c-border-input)] rounded-lg bg-[var(--c-bg-input)] text-[var(--c-text)] font-mono text-[0.8rem] outline-none resize-y min-h-[80px] transition-[border-color,box-shadow] focus:border-[var(--c-accent-focus)] focus:shadow-[0_0_0_3px_var(--c-accent-ring)]";
const fieldSelectClass =
  "w-full px-2.5 py-1.5 border border-[var(--c-border-input)] rounded-lg bg-[var(--c-bg-input)] text-[var(--c-text)] text-sm cursor-pointer outline-none";
const cancelBtnClass =
  "px-5 py-2.5 rounded-xl border border-[var(--c-border-input)] bg-[var(--c-bg-cancel-btn)] text-[var(--c-text-secondary)] text-sm font-semibold cursor-pointer transition-colors hover:bg-[var(--c-bg-input)]";

const numericTypes = new Set([
  "integer",
  "bigint",
  "smallint",
  "float4",
  "float8",
  "numeric",
  "real",
  "double precision",
]);

/** Returns true when the DB auto-generates this column's value on insert. */
function isAutoGeneratedColumn(column: TableColumnInfo) {
  // Identity columns (GENERATED ALWAYS or BY DEFAULT)
  if (column.identityGeneration) return true;
  // Sequences (serial / bigserial)
  if (column.defaultValue?.includes("nextval(")) return true;
  // Function-based defaults on PK columns (gen_random_uuid, uuid_generate_v4, etc.)
  if (column.isPrimaryKey && column.defaultValue?.includes("()")) return true;
  return false;
}

function isJsonInputColumn(column: TableColumnInfo) {
  const type = column.dataType.toLowerCase();
  const name = column.name.toLowerCase();
  return type === "json" || type === "jsonb" || name === "vector" || name.includes("embedding") || name === "metadata";
}

function isBooleanColumn(column: TableColumnInfo) {
  return column.dataType.toLowerCase() === "boolean";
}

function isNumberColumn(column: TableColumnInfo) {
  return numericTypes.has(column.dataType.toLowerCase());
}

function isRequiredColumn(column: TableColumnInfo) {
  if (isAutoGeneratedColumn(column)) return false;
  if (column.isPrimaryKey) return true;
  return !column.isNullable && !column.defaultValue;
}

export function InsertRowButton({ connectionId, schemaName, tableName, columns, canMutate }: Props) {
  const [pending, startTransition] = useTransition();
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!canMutate) return null;

  const editableColumns = columns.filter((column) => !isAutoGeneratedColumn(column));

  const onInsert = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const values: Record<string, unknown> = {};

    for (const column of editableColumns) {
      const raw = (formData.get(column.name) as string | null) ?? "";
      const trimmed = raw.trim();
      const required = isRequiredColumn(column);

      if (trimmed === "") {
        if (column.isNullable) {
          values[column.name] = null;
        } else if (required) {
          setError(`${column.name} is required.`);
          return;
        }
        continue;
      }

      if (isBooleanColumn(column)) {
        if (trimmed === "null") {
          values[column.name] = null;
        } else {
          values[column.name] = trimmed === "true";
        }
        continue;
      }

      if (isNumberColumn(column)) {
        const parsed = Number(trimmed);
        if (Number.isNaN(parsed)) {
          setError(`${column.name} must be a valid number.`);
          return;
        }
        values[column.name] = parsed;
        continue;
      }

      if (isJsonInputColumn(column)) {
        try {
          JSON.parse(trimmed);
          // Store as string, not parsed object, to avoid serialization issues
          values[column.name] = trimmed;
        } catch {
          setError(`${column.name} must be valid JSON.`);
          return;
        }
        continue;
      }

      values[column.name] = raw;
    }

    setError(null);
    startTransition(async () => {
      const result = await insertTableRow({
        connectionId,
        schemaName,
        tableName,
        values,
      });
      if (result.error) {
        setError(result.error);
        return;
      }
      window.location.reload();
    });
  };

  return (
    <div className="flex flex-col gap-3">
      <button
        type="button"
        onClick={() => {
          setShowForm((prev) => !prev);
          setError(null);
        }}
        disabled={pending}
        className="w-fit px-4 py-2.5 rounded-xl border-0 bg-gradient-to-br from-accent to-accent-strong text-[var(--c-text-on-accent)] text-sm font-bold cursor-pointer disabled:opacity-70"
      >
        {showForm ? "Cancel Insert" : "+ Insert Row"}
      </button>

      {showForm && (
        <article className="border border-[var(--c-accent-ring)] shadow-[0_0_0_3px_var(--c-accent-bg-active)] rounded-[20px] bg-[var(--c-bg-card)] overflow-hidden">
          <form className="p-5 px-6" onSubmit={onInsert}>
            <div className="flex items-start gap-3 mb-4 flex-wrap">
              <span className="inline-flex items-center px-2.5 py-0.5 rounded-full bg-[var(--c-tag-bg)] font-mono text-[0.72rem] text-[var(--c-text-muted)] shrink-0">
                New row
              </span>
              <h3 className="flex-1 m-0 text-[1.05rem] font-bold text-[var(--c-text-muted)] italic leading-[1.35]">
                Insert into {schemaName}.{tableName}
              </h3>
            </div>

            <div className="grid grid-cols-[repeat(auto-fill,minmax(180px,1fr))] gap-3">
              {editableColumns.map((column) => {
                const required = isRequiredColumn(column);
                const isJson = isJsonInputColumn(column);
                const isBoolean = isBooleanColumn(column);
                const isNumber = isNumberColumn(column);

                return (
                  <div key={column.name} className={`flex flex-col gap-1 ${isJson ? "col-span-full" : ""}`}>
                    <span className={fieldLabelClass}>
                      {column.name}
                      {required ? " *" : ""}
                    </span>

                    {isBoolean ? (
                      <select
                        name={column.name}
                        className={fieldSelectClass}
                        defaultValue={column.isNullable ? "null" : "false"}
                      >
                        {column.isNullable && <option value="null">NULL</option>}
                        <option value="true">true</option>
                        <option value="false">false</option>
                      </select>
                    ) : isJson ? (
                      <textarea
                        name={column.name}
                        className={fieldTextareaClass}
                        rows={4}
                        required={required}
                        placeholder={column.isNullable ? "Leave blank for NULL or provide valid JSON" : "Provide valid JSON"}
                      />
                    ) : (
                      <input
                        name={column.name}
                        className={fieldInputClass}
                        type={isNumber ? "number" : "text"}
                        step={isNumber ? "any" : undefined}
                        required={required}
                      />
                    )}
                  </div>
                );
              })}
            </div>

            {error && (
              <p className="px-3.5 py-2.5 rounded-[10px] bg-[var(--c-danger-bg)] border border-[var(--c-danger-border)] text-[var(--c-danger-text)] text-sm mt-3">
                {error}
              </p>
            )}

            <div className="flex gap-2.5 mt-5 pt-4 border-t border-[var(--c-border)]">
              <button
                className="px-5 py-2.5 rounded-xl border-0 bg-gradient-to-br from-accent to-accent-strong text-[var(--c-text-on-accent)] text-sm font-bold cursor-pointer transition-opacity disabled:opacity-70 disabled:cursor-wait"
                type="submit"
                disabled={pending}
              >
                {pending ? "Inserting..." : "Insert row"}
              </button>
              <button
                className={cancelBtnClass}
                type="button"
                onClick={() => {
                  setShowForm(false);
                  setError(null);
                }}
                disabled={pending}
              >
                Cancel
              </button>
            </div>
          </form>
        </article>
      )}
    </div>
  );
}
